### ISSUE TITLE
2.3 uwagi

### ISSUE THREAD

**Issue by MARudnicki** [Magdalena-Cieslak/magdalena_cieslak-kodilla_tester#1]
Notebook.checkPrice
- jesli price == 600, to wpadnie w warunek is expensive, a powinien cheap lub good
- typo expensive nie expencive

Notebook.checkWeight
- warunek `this.weight > 600 && this.weight <= 1600`. Pierwszy warunek jest niepotrzebny, bo zawsze bedzie spelniony. Wpadnie w pierwsze case `this.weight <= 600`

String'i porownujemy poprzez equals
np `"one".equals("second")`. Przypomij mi to pokaze Ci na spotkaniu dlaczego

Znaki jak < >= itd stosujemy tylko do typow numerycznych. Uzycie int'a jest ok.
W razie czego mozna robic konwercje typow
```
Integer.valueOf("123");
String.valueOf(123)
```

**Comment by Magdalena-Cieslak** [comment]
Ok, zgadza się. Czy mam ponownie wysłać poprawiony kod do githuba? Bo nie widzę możliwości edycji tutaj żeby poprawić.
